name: responsive_notebook_background
description: A notebook background which is responsive to the system text size settings.
homepage: https://pub.dev/publishers/cosee.biz/packages
version: 1.0.1
repository: https://github.com/cosee/responsive_notebook_background/tree/main
issue_tracker: https://github.com/cosee/responsive_notebook_background/issues
screenshots:
  - description: 'Default appearance of ResponsiveNotebookBackground'
    path: 'example/screenshots/lined.webp'
topics:
  - background
  - notebook
  - responsive

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  cosee_lints: ^0.8.0
  dart_code_linter: ^2.0.0
