name: responsive_notebook_background
description: A notebook background which is responsive to the system text size settings.
homepage: https://pub.dev/publishers/cosee.biz/packages
version: 0.1.5
repository: https://github.com/cosee/responsive_notebook_background
issue_tracker: https://github.com/cosee/responsive_notebook_background/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  cosee_lints: ^0.2.0
  dart_code_metrics: ^5.5.1

flutter: