name: responsive_notebook_background
description: A notebook background which is responsive to the system text size settings.
version: 0.1.2
repository: https://github.com/cosee/responsive_notebook_background

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  dart_code_metrics: ^4.8.1

flutter: