blank_issues_enabled: false
contact_links:
  - name: Request help
    url: https://github.com/cosee/responsive_notebook_background/discussions/categories/request-help
    about: Need assistance or guidance with the responsive_notebook_background package? We're here to help!
